version: '3'

services:
  little-pig-bot-app:
    build: .
    image: little-pig-bot-0.0.1
    container_name: little-pig-bot
    ports:
      - 1488:1488
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 8001:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notedb
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped

volumes:
  pg-data: