spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:32769/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 1488

connection:
  token:
  username:
