spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres-db:5432/notedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 1488

telegram:
  bot:
    token:

