apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  postgresHost: postgres
  postgresName: notedb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redisHost: redis-service
